repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
        args: [--verbose]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: format-json
        name: Format JSON
        description: "Format JSON"
        files: ^.*\.json$
        types_or: [json]
        entry: dprint
        language: system
        args:
          - "fmt"
          - "--allow-no-files"

      - id: format-markdown
        name: Format Markdown
        description: "Format Markdown"
        files: ^.*\.md$
        types_or: [markdown]
        entry: dprint
        language: system
        args:
          - "fmt"
          - "--allow-no-files"

      - id: format-yaml
        name: Format YAML
        description: "Format YAML"
        files: ^.*\.(yaml|yml)$
        types_or: [yaml]
        entry: dprint
        language: system
        args:
          - "fmt"
          - "--allow-no-files"

      - id: format-toml
        name: Format TOML
        description: "Format TOML"
        files: ^.*\.toml$
        types_or: [toml]
        entry: dprint
        language: system
        args:
          - "fmt"
          - "--allow-no-files"
